// 「长拳”为寻常的拳脚功夫, 一般拳师、保镖都可以挂上去。
// 由于是 NPC 专用的 SKILL, 故省略 valid_learn 与 practice_skill 的设定
// make by Onion
#include <combat.h>
inherit SKILL;

mapping *action = ({
([ "action":"$N双手如勾，一招「金龙探爪”，身形如一条金龙往$n$l攻了过去",
	"dodge": -3,
	"parry": -2,
	"damage": 25,
	"force":  40,
	"damage_type":	"割伤",
]),

([ "action":"$N气沉丹田，「龙行一式”蓄势待发，一拳打向$n的$l",
	"dodge": -4,
	"parry": -5,
        "damage": 22,
        "force": 30,
	"damage_type": "瘀伤",
]),

([ "action":"$N身形一转，使出「秋风落叶”，向$n$l横扫而去",
	"dodge": -5,
	"parry": -2,
        "damage": 20,
       	"force": 40,
	"damage_type": "瘀伤",
]),
([ "action":"$N击出「龙门三击浪”，拳劲直直的撞向$n$l",
	"dodge": 5,
	"parry": 0,
        "damage": 70,
       	"force": 50,
	"damage_type": "瘀伤",
]),
([ "action":"$N突然一招「翻身打盘”，身形刁钻的朝$n$l一拳直去",
	"dodge": 0,
	"parry": -2,
        "damage": 10,
       	"force": 30,
	"damage_type": "瘀伤",
]),
([ "action":"$N双手一展，使出「金鵰展翅”，由上而下拳打$n$l",
	"dodge": -5,
	"parry": -2,
        "damage": 20,
       	"force": 30,
	"damage_type": "瘀伤",
	
]),
([ "action":"$N大喝一声，「苍龙归海”，双手缓缓的推向$n$l",
	"dodge": -5,
	"parry": -2,
        "damage": 29,
       	"force": 30,
	"damage_type": "瘀伤",
]),
([ "action":"$N势如猛虎出闸，「黑虎偷心”直袭$n$l",
        "dodge": -3,
        "parry": -2,
        "damage": 20,
        "force":  40,
        "damage_type":  "瘀伤",
]),

([ "action":"$N使出「进步连环”，一连三拳打向$n$l",
        "dodge": -4,
        "parry": -1,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀伤",
]),

([ "action":"$N斥喝一声，使出「独劈华山”，一掌向$n斩了下去",
        "dodge": -5,
        "parry": 0,
        "damage": 70,
        "force": 4,
        "damage_type": "瘀伤",
]),
([ "action":"$N身形一退，一招「倒打金钟”反而打向$n$l",
        "dodge": 5,
        "parry": 0,
        "damage": 80,
        "force": 5,
        "damage_type": "瘀伤",
]),
([ "action":"$N一转身，「黄龙卷尾”一拳向$n$l飞去",
        "dodge": -3,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀伤",
]),
([ "action":"$N一招「如封似闭”，双手忽上忽下，游移不定的击向$n$l",
        "dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀伤",
]),
([ "action":"$N右手往前一推，一招「推窗望月”向$n推去",
	"dodge": -5,
	"parry": -2,
	"damage": 20,
	"force": 3,
	"damage_type":"瘀伤",
]),
([ "action":"$N左手阴拳，打出一招「白猿摘果”，直袭$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀伤",
]),
([ "action":"$N身形一扭，使出「玉带围腰”，拳背直击$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀伤",
]),
([ "action":"$N双手握拳，「抽撤连环”向$n$l击去",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀伤",
          ]),
([ "action":"$N双手合掌，「寒鸡拜佛”刺向$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"刺伤",
]),
});

mapping query_action(object me, object weapon)
{
	  return action[random(sizeof(action))];
}

int valid_enable(string usage) 
{
	  return (usage=="unarmed");
}
