
mapping basic_skill = ([
		"array"		:	"array",
		"axe"		:	"axe",
		"be-officer"	:	"be-officer",
		"blade"		:	"blade",
		"cure"		:	"cure",
		"dagger"	:	"dagger",
		"dodge"		:	"dodge",
		"force"		:	"force",
		"gamble"	:	"gamble",
		"gmagic"	:	"gmagic",
		"hammer"	:	"hammer",
		"literate"	:	"literate",
		"magic"		:	"magic",
		"move"		:	"move",
		"parry"		:	"parry",
		"plan"		:	"plan",
		"poison"	:	"poison",
		"spells"	:	"spells",
		"stabber"	:	"stabber",
		"staff"		:	"staff",
        "striback"  :   "striback",
		"stick"		:	"stick",
		"sword"		:	"sword",
		"throwing"	:	"throwing",
		"trade"		:	"trade",
		"unarmed"	:	"unarmed",
		"whip"		:	"whip",
                "lance"         :       "lance",
		"archery"  :  "archery",
				]);
