inherit ROOM;
void create() {
	set( "short", "$YEL$in utero$NOR$" );
	set( "owner", "nirvana" );
	set( "build", 10500 );
	set( "exits", ([
		"south"     : "/open/clan/hell/room/room46.c",
		"east"      : "/open/clan/hell/room/room47",
		"west"      : "/open/clan/hell/room/room55",
	]) );
	set( "light_up", 1 );
	set( "long", @LONG
kalin大二时....渐渐迷上pink floyed..
其实在高三时kalin就在听他们了....
只是这时特别对他们有感觉....
也开始收集60 70年代的其他专辑....
除此之□..kalin对英国乐团也特别有兴趣....
对音乐的态度也有所改观了...
这好像又是一个转折点....
虽然花了许多钱跟心血....
kalin仍津津乐道在此........
LONG);
	setup();
	replace_program(ROOM);
}
